name: inSTA
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0-0'

dependencies:
  flutter:
    sdk: flutter

  # ============================================
  # Mobile (Android & iOS) + Web Compatible
  # ============================================
  animations: ^2.1.0
  awesome_snackbar_content: ^0.1.8
  boxy: ^2.2.2
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.2.0
  emoji_picker_flutter: ^4.4.0
  extended_nested_scroll_view: ^6.2.1
  dots_indicator: ^4.0.1
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  fluentui_system_icons: ^1.1.273
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.12.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  hooks_riverpod: ^2.6.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_serializable: ^6.9.5
  logger: ^2.6.2
  lottie: ^3.3.2
  package_info_plus: ^8.3.1
  pin_code_fields: ^8.0.1
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  sprintf: ^7.0.0
  uuid: ^4.5.2

  # ============================================
  # Mobile Only (Android & iOS)
  # ============================================

  restart: ^1.0.0
  firebase_crashlytics: ^5.0.4
  firebase_auth: ^6.1.2

dev_dependencies:
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false

    #style: camel-case

  fonts:
    enabled: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appicon/app_icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/appicon/
    - assets/images/
    - assets/images/profile/
    - assets/lottie/
